server:
   port: 8095
spring:
   datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: tiger
        url: jdbc:mysql://localhost:3306/PaymentDB
        username: root    
   jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
            format_sql: true
        show-sql: true           
   application:
      name: PAYMENT-SERVICE
   config:
      import: optional:configserver:http://localhost:9296
management:
   tracing:
      sampling:
         probability: 1